import { SITE_ADAPTERS } from '../src/extraction/adapters/registry';
import type { SiteAdapter } from '../src/extraction/adapters/types';

const KIND_TITLE: Record<SiteAdapter['kind'], string> = {
  'job-board': 'Job boards',
  aggregator: 'Aggregators',
  government: 'Government',
  ats: 'Applicant tracking systems (ATS)',
};

function hosts(adapter: SiteAdapter): string {
  return adapter.hosts
    .map((h) => (typeof h === 'string' ? `\`${h}\`` : `\`/${h.source}/\``))
    .join(', ')
    .replace(/\|/g, '\\|');
}

function features(adapter: SiteAdapter): string {
  const f: string[] = [];
  if (adapter.canonicalUrl) f.push('canonical URL');
  if (adapter.externalId) f.push('job id');
  if (adapter.selectors) f.push(`${Object.keys(adapter.selectors).length} selector fields`);
  if (adapter.titlePatterns?.length) f.push('title pattern');
  if (adapter.companyFromUrl) f.push('company from URL');
  if (adapter.detect) f.push('custom-domain detection');
  if (adapter.extract) f.push('custom logic');
  return f.join(', ');
}

export function renderSupportedSites(): string {
  const lines: string[] = [
    '# Supported sites',
    '',
    '<!-- GENERATED by `npm run docs:sites` from src/extraction/adapters. Do not edit by hand. -->',
    '',
    `Rolestash ships **${SITE_ADAPTERS.length} site adapters**. Any other site still works through`,
    'the generic layers (JSON-LD → microdata → meta/heuristics); adapters add precision,',
    'canonical URLs for duplicate detection, and support for pages without structured data.',
    '',
    '**Verified** means the adapter was checked against the live site and a real fixture',
    'is committed. "—" means best-effort: written from knowledge of the site’s markup and',
    'covered by synthetic tests only. See [adding a site adapter](../guides/adding-a-site-adapter.md).',
    '',
  ];
  for (const kind of Object.keys(KIND_TITLE) as SiteAdapter['kind'][]) {
    const group = SITE_ADAPTERS.filter((a) => a.kind === kind).sort((a, b) =>
      a.name.localeCompare(b.name),
    );
    if (group.length === 0) continue;
    lines.push(`## ${KIND_TITLE[kind]} (${group.length})`, '');
    lines.push('| Site | Id | Regions | Hosts | Adapter features | Verified |');
    lines.push('| --- | --- | --- | --- | --- | --- |');
    for (const a of group) {
      lines.push(
        `| [${a.name}](${a.homepage}) | \`${a.id}\` | ${a.regions.join(', ')} | ${hosts(a)} | ${features(a)} | ${a.lastVerified ?? '—'} |`,
      );
    }
    lines.push('');
  }
  const notes = SITE_ADAPTERS.filter((a) => a.notes).sort((a, b) => a.name.localeCompare(b.name));
  lines.push('## Site notes', '');
  for (const a of notes) lines.push(`- **${a.name}** — ${a.notes ?? ''}`);
  lines.push('');
  return lines.join('\n');
}
